
import React, { useEffect, useMemo, useState, useRef } from 'react';
import { useStore } from '@/features/system/context/GlobalStore';
import { ProductType, Bundle, Product, OptionVariant, OptionType, MachineConfigEntry, Currency } from '@/types';
import { Box, ChevronDown, ChevronRight, CheckCircle, Circle, Calculator, Save, ShieldCheck, Tag, PieChart, Settings, Search, X, ListFilter, Star, Download } from 'lucide-react';
import { useBundleConfigurator } from '@/features/bundles/hooks/useBundleConfigurator';
import { PricingService } from '@/services/PricingService';
import { BundleCalculator } from '@/services/BundleCalculator';
import { BundleExporter } from '@/services/BundleExporter';
import { ApiService } from '@/services/api';
import { useAccess } from '@/features/auth/hooks/useAccess';

interface ConfiguratorBuilderProps {
  onSaved: () => void;
  editingBundle?: Bundle | null;
}

export const ConfiguratorBuilder: React.FC<ConfiguratorBuilderProps> = ({ onSaved, editingBundle }) => {
  const { state, actions } = useStore();
  const access = useAccess('bundles');
  const { products, optionTypes, optionVariants, exchangeRates, pricingProfiles, categories } = state;
  const config = useBundleConfigurator();

  const [modelSearch, setModelSearch] = useState('');
  const [isModelDropdownOpen, setIsModelDropdownOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const machine = products.find(p => p.id === config.baseMachineId);
  const canSave = access.canWrite('actions', 'save_template');
  const showEconomy = access.canSee('fields', 'economy_details');

  const [isDescExpanded, setIsDescExpanded] = useState(false);
  const [userMargin, setUserMargin] = useState<number | null>(null);

  const filteredModels = useMemo(() => {
    return products.filter(p => {
      const isMachine = p.type === ProductType.MACHINE;
      const matchesCategory = !config.categoryId || p.categoryId === config.categoryId;
      const matchesSearch = !modelSearch || 
                           p.name.toLowerCase().includes(modelSearch.toLowerCase()) || 
                           p.sku.toLowerCase().includes(modelSearch.toLowerCase());
      return isMachine && matchesCategory && matchesSearch;
    });
  }, [products, config.categoryId, modelSearch]);

  const autoGeneratedName = useMemo(() => {
    if (!machine) return '';
    const selectedVariantNames = (Object.values(config.selectedOptions) as string[][])
      .flat()
      .map(vid => optionVariants.find(v => v.id === vid)?.name)
      .filter(Boolean);
    
    return selectedVariantNames.length > 0 
      ? `${machine.name} [${selectedVariantNames.join(' + ')}]`
      : machine.name;
  }, [machine, config.selectedOptions, optionVariants]);

  useEffect(() => {
    if (editingBundle) {
        const baseProd = products.find(p => p.id === editingBundle.baseProductId);
        if (baseProd?.categoryId) config.setCategoryId(baseProd.categoryId);
        
        config.setBaseMachineId(editingBundle.baseProductId);
        config.setBundleName(editingBundle.name);
        config.setBundleDescription(editingBundle.description || '');
        const restoredOptions: Record<string, string[]> = {};
        editingBundle.selectedVariantIds.forEach(vid => {
            const variant = optionVariants.find(v => v.id === vid);
            if (variant) {
                if (!restoredOptions[variant.typeId]) restoredOptions[variant.typeId] = [];
                restoredOptions[variant.typeId].push(vid);
            }
        });
        config.setSelectedOptions(restoredOptions);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [editingBundle]);

  useEffect(() => {
    if (machine && machine.machineConfig && !editingBundle) {
      const defaults: Record<string, string[]> = {};
      const allTypeIds: string[] = [];
      machine.machineConfig.forEach(c => {
        allTypeIds.push(c.typeId);
        const defaultIds = BundleCalculator.getDefaultIds(c);
        if (defaultIds.length > 0) {
            defaults[c.typeId] = defaultIds;
        }
      });
      config.setSelectedOptions(defaults);
      config.setExpandedTypeIds(allTypeIds);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [machine?.id]);

  useEffect(() => {
    setUserMargin(null);
  }, [machine?.id]);

  const defaultMargin = useMemo(() => {
    if (!machine) return null;
    const profile = PricingService.findProfile(machine, pricingProfiles);
    return profile ? profile.targetNetMarginPercent : (machine.markupPercentage || null);
  }, [machine, pricingProfiles]);

  const marginOverride = userMargin ?? defaultMargin;

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsModelDropdownOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const bundleTotals = useMemo(() => {
    if (!machine) return { purchaseTotal: 0, totalVolume: 0 };
    const totals = BundleCalculator.calculateTotals(machine, config.selectedOptions, optionVariants, exchangeRates as any);
    return { purchaseTotal: totals.purchaseTotal, totalVolume: totals.totalVolumeM3 };
  }, [machine, config.selectedOptions, optionVariants, exchangeRates]);


  const economy = useMemo(() => {
    if (!machine) return null;
    const profile = PricingService.findProfile(machine, pricingProfiles);
    const data = PricingService.calculateSmartPrice(machine, profile, exchangeRates, bundleTotals.totalVolume, bundleTotals.purchaseTotal, marginOverride ?? undefined);
    return { profile, data, purchaseForeign: bundleTotals.purchaseTotal, totalVolume: bundleTotals.totalVolume };
  }, [machine, pricingProfiles, exchangeRates, marginOverride, bundleTotals]);

  const handleSave = async () => {
    if (!machine || !canSave) return;
    
    const finalName = config.bundleName.trim() || autoGeneratedName;
    if (!finalName) return;

    const bundleData: Bundle = {
      id: editingBundle?.id || ApiService.generateId(),
      name: finalName,
      baseProductId: machine.id,
      baseProductName: machine.name,
      selectedVariantIds: (Object.values(config.selectedOptions) as string[][]).flat(),
      totalPurchasePrice: economy?.purchaseForeign || 0,
      totalPrice: economy?.data?.finalPrice || 0,
      isTemplate: true,
      description: config.bundleDescription
    };
    
    if (editingBundle) await actions.updateBundle(bundleData);
    else await actions.addBundle(bundleData);
    onSaved();
  };

  const handleExport = () => {
    if (!machine) return;
    BundleExporter.exportToCsv(
      {
        name: config.bundleName || autoGeneratedName,
        baseProductId: machine.id,
        selectedVariantIds: (Object.values(config.selectedOptions) as string[][]).flat(),
        totalPrice: economy?.data?.finalPrice || 0,
        description: config.bundleDescription
      },
      products,
      optionVariants,
      optionTypes,
      (module, sub, id, msg) => actions.addLog(module, sub, id, msg)
    );
  };

  const f = (val: number) => Math.round(val).toLocaleString();

  return (
    <div className="flex h-full gap-5 overflow-hidden">
      {/* LEFT COLUMN: SELECTION & OPTIONS */}
      <div className="flex-1 flex flex-col min-h-0 space-y-3">
        
        <div className="bg-white p-3 rounded-2xl shadow-sm border border-slate-200 flex-none space-y-2.5">
          <div className="grid grid-cols-12 gap-3 items-end">
            <div className="col-span-4">
              <label className="block text-[8px] font-black text-slate-400 uppercase mb-1 ml-1 tracking-widest flex items-center gap-1.5">
                <ListFilter size={10}/> КАТЕГОРИЯ
              </label>
              <select 
                className="w-full border border-slate-200 py-1.5 px-2.5 rounded-lg text-xs font-bold text-slate-700 bg-slate-50 focus:ring-2 focus:ring-blue-500/10 outline-none transition-all"
                value={config.categoryId}
                onChange={e => { config.setCategoryId(e.target.value); config.setBaseMachineId(''); setModelSearch(''); }}
                disabled={!!editingBundle}
              >
                <option value="">Все категории</option>
                {categories.filter(c => c.type === ProductType.MACHINE).map(c => (
                  <option key={c.id} value={c.id}>{c.name}</option>
                ))}
              </select>
            </div>

            <div className="col-span-8 relative" ref={dropdownRef}>
              <label className="block text-[8px] font-black text-slate-400 uppercase mb-1 ml-1 tracking-widest flex items-center gap-1.5">
                <Box size={10}/> МОДЕЛЬ СТАНКА
              </label>
              <div className="relative">
                <Search size={12} className="absolute left-2.5 top-2.5 text-slate-300 pointer-events-none"/>
                <input 
                  type="text"
                  className={`w-full border border-slate-200 pl-8 pr-10 py-1.5 rounded-lg text-xs font-black outline-none transition-all focus:ring-2 focus:ring-blue-500/10 ${
                    !modelSearch && machine ? 'text-blue-600 bg-blue-50/30' : 'text-slate-800 bg-white'
                  } placeholder:text-slate-300 disabled:opacity-75`}
                  placeholder={machine ? machine.name : "Начните вводить название..."}
                  value={modelSearch || (!isModelDropdownOpen && machine ? machine.name : '')}
                  onFocus={() => setIsModelDropdownOpen(true)}
                  onChange={e => { setModelSearch(e.target.value); setIsModelDropdownOpen(true); }}
                  disabled={!!editingBundle}
                />
                {machine && !editingBundle && (
                  <button onClick={() => { config.setBaseMachineId(''); setModelSearch(''); }} className="absolute right-2 top-2 p-0.5 text-slate-300 hover:text-red-500 transition-colors"><X size={14}/></button>
                )}
              </div>

              {isModelDropdownOpen && !editingBundle && (
                <div className="absolute top-full left-0 right-0 mt-1 bg-white rounded-xl shadow-2xl border border-slate-100 z-[100] max-h-60 overflow-y-auto animate-in fade-in slide-in-from-top-1 duration-200">
                  {filteredModels.length > 0 ? (
                    filteredModels.map(p => (
                      <div 
                        key={p.id} 
                        onClick={() => { config.resetSelection(p.id); setIsModelDropdownOpen(false); setModelSearch(''); }}
                        className="px-4 py-2 hover:bg-blue-50 cursor-pointer text-xs font-bold text-slate-700 border-b last:border-0 flex justify-between items-center group"
                      >
                        <span className="group-hover:text-blue-600 transition-colors">{p.name}</span>
                        <span className="text-[9px] font-mono text-slate-300 uppercase">{p.sku}</span>
                      </div>
                    ))
                  ) : (
                    <div className="p-4 text-center text-[10px] font-bold text-slate-400 uppercase italic">Модели не найдены</div>
                  )}
                </div>
              )}
            </div>
          </div>

          <div className="relative">
            <label className="block text-[8px] font-black text-blue-500 uppercase mb-1 ml-1 tracking-widest flex items-center gap-1.5">
              <Tag size={10}/> НАЗВАНИЕ СБОРКИ
            </label>
            <input 
              className="w-full border border-slate-200 py-1.5 px-3 rounded-lg text-xs font-black text-slate-700 bg-white focus:ring-2 focus:ring-blue-500/10 outline-none transition-all placeholder:text-slate-400 placeholder:italic" 
              placeholder={autoGeneratedName || "Название будет сгенерировано автоматически..."} 
              value={config.bundleName} 
              onChange={e => config.setBundleName(e.target.value)}
              disabled={!machine}
            />
          </div>
        </div>

        <div className="flex-1 overflow-y-auto pr-1.5 custom-scrollbar space-y-2.5">
          {!machine ? (
            <div className="h-full flex flex-col items-center justify-center text-slate-300 bg-white rounded-3xl border-2 border-dashed border-slate-100 opacity-50">
               <Box size={40} className="mb-3 text-slate-200"/>
               <p className="text-[9px] font-black uppercase tracking-widest text-center">Выберите модель станка<br/>чтобы начать сборку</p>
            </div>
          ) : (
            <>
              <div className="flex items-baseline gap-2 mb-1 px-1">
                 <span className="text-[11px] font-black text-slate-700 uppercase">{machine.name}</span>
                 <span className="text-[9px] font-mono text-slate-400 uppercase">{machine.sku}</span>
              </div>
              
              {machine.machineConfig && optionTypes
                .filter(ot => {
                  const configEntry = machine.machineConfig?.find(mc => mc.typeId === ot.id);
                  return configEntry && configEntry.allowedVariantIds && configEntry.allowedVariantIds.length > 0;
                })
                .map(type => {
                const isExpanded = config.expandedTypeIds.includes(type.id);
                const selectedVars = config.selectedOptions[type.id] || [];
                const configEntry = machine.machineConfig?.find(mc => mc.typeId === type.id);
                const allowedVarIds = configEntry?.allowedVariantIds || [];
                const variants = optionVariants.filter(v => v.typeId === type.id && allowedVarIds.includes(v.id));

                return (
                  <div key={type.id} className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden transition-all">
                    <div className={`p-2.5 flex justify-between items-center cursor-pointer hover:bg-slate-50 ${isExpanded ? 'border-b bg-slate-50/30' : ''}`} onClick={() => config.toggleAccordion(type.id)}>
                      <div className="flex items-center gap-2.5">
                        <div className={`p-1.5 rounded-lg ${selectedVars.length > 0 ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-400'}`}><Settings size={12}/></div>
                        <span className="font-black text-xs uppercase text-slate-700 tracking-tight">{type.name}</span>
                        {selectedVars.length > 0 && <span className="bg-blue-50 text-blue-600 text-[8px] px-1.5 py-0.5 rounded-md font-black uppercase">Выбрано</span>}
                      </div>
                      {isExpanded ? <ChevronDown size={14} className="text-slate-300"/> : <ChevronRight size={14} className="text-slate-300"/>}
                    </div>
                    {isExpanded && (
                      <div className="p-2.5 grid grid-cols-2 lg:grid-cols-3 gap-2 bg-slate-50/20">
                        {variants.map(v => 
                            <OptionCard key={v.id} type={type} v={v} machine={machine} configEntry={configEntry} selectedVars={selectedVars} exchangeRates={exchangeRates} access={access} config={config} f={f} />
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
            </>
          )}
        </div>
      </div>

      <div className="w-[320px] flex flex-col bg-white rounded-3xl shadow-2xl border border-slate-200 overflow-hidden flex-none h-full">
        {machine && economy ? (
          <div className="flex flex-col h-full overflow-hidden">
            <div className="p-3.5 bg-slate-900 text-white flex-none flex flex-col items-center justify-center border-b border-white/5 relative">
              <div className="text-[9px] font-black text-slate-400 uppercase tracking-[0.2em] mb-0.5">Итоговая цена продажи</div>
              <div className="text-2xl font-black font-mono tracking-tight flex items-baseline gap-1">
                {f(economy.data?.finalPrice || 0)} <span className="text-[11px] font-medium text-blue-400 uppercase">KZT</span>
              </div>
              <button 
                onClick={handleExport}
                className="absolute top-3 right-3 p-2 text-slate-500 hover:text-white hover:bg-white/10 rounded-xl transition-all"
                title="Скачать комплектацию"
              >
                <Download size={18}/>
              </button>
              <div className="mt-2 grid grid-cols-3 text-center divide-x divide-white/10 w-full">
                <div className="px-2">
                  <div className="text-[8px] font-black text-slate-400 uppercase tracking-[0.1em]">Объем</div>
                  <div className="text-sm font-black font-mono text-white">{economy.totalVolume.toFixed(2)} <span className="text-[9px] text-slate-300">m³</span></div>
                </div>
                <div className="px-2">
                  <div className="text-[8px] font-black text-slate-400 uppercase tracking-[0.1em]">Базовая закупка</div>
                  <div className="text-sm font-black font-mono text-cyan-300">{f(machine.basePrice)} <span className="text-[9px] text-cyan-500">{machine.currency}</span></div>
                </div>
                <div className="px-2">
                  <div className="text-[8px] font-black text-slate-400 uppercase tracking-[0.1em]">Итоговая закупка</div>
                  <div className="text-sm font-black font-mono text-amber-300">{f(economy.purchaseForeign)} <span className="text-[9px] text-amber-500">{machine.currency}</span></div>
                </div>
              </div>
            </div>

            <div onClick={() => setIsDescExpanded(false)} className="flex-1 overflow-y-auto custom-scrollbar p-3.5 space-y-3.5 cursor-default">
              {showEconomy ? (
                <>
                  <div className="flex justify-between items-center bg-slate-50 p-2.5 rounded-lg border border-slate-200">
                    <div className="flex items-center gap-2 overflow-hidden">
                        <ShieldCheck size={12} className="text-blue-500 flex-shrink-0"/>
                        <span className="text-[11px] font-black text-slate-700 truncate uppercase tracking-tight">{economy.profile?.name || 'Ручная наценка'}</span>
                    </div>
                    <input 
                        type="number" 
                        className="w-20 bg-white border border-slate-200 rounded text-center text-[10px] font-black uppercase text-slate-700 p-1 outline-none focus:ring-2 ring-blue-500/20"
                        value={userMargin ?? ''}
                        onChange={(e) => setUserMargin(e.target.value ? parseFloat(e.target.value) : null)}
                        placeholder={`${defaultMargin ?? 0}%`}
                    />
                  </div>

                  <div className="border-l-2 border-blue-500 pl-2.5 space-y-1">
                      <DetailRow label="Цена закупки" value={economy.data.purchaseKzt} bold color="text-slate-900" />
                      <DetailRow label="Логистика (Китай)" value={economy.data.logisticsCn} />
                      <DetailRow label="Логистика (Местная)" value={economy.data.logisticsLocal} />
                  </div>

                  <div className="border-l-2 border-orange-500 pl-2.5 space-y-1">
                      <DetailRow label="Склад / Терминал" value={economy.data.svh} />
                      <DetailRow label="Таможня / Брокер" value={economy.data.customsFees + economy.data.brokerFees} />
                  </div>

                  <div className="border-l-2 border-purple-500 pl-2.5 space-y-1">
                      <DetailRow label="Пусконаладка" value={economy.data.pnr} />
                      <DetailRow label="Доставка клиенту" value={economy.data.deliveryLocal} />
                      <DetailRow label="Бонус отдела продаж" value={economy.data.bonus} color="text-purple-600" />
                  </div>

                  <div className="border-l-2 border-red-500 pl-2.5 space-y-1">
                      <DetailRow label={`НДС (${economy.profile?.vatRate || 12}%)`} value={economy.data.vat} />
                      <DetailRow label={`КПН (${economy.profile?.citRate || 20}%)`} value={economy.data.cit} />
                  </div>

                  <div className="pt-2.5 border-t border-slate-100 space-y-2">
                      <div className="flex justify-between items-center text-slate-500 px-1">
                          <span className="text-[10px] font-black uppercase tracking-widest">Всего расходов:</span>
                          <span className="text-xs font-black font-mono">{f(economy.data.totalExpenses)} ₸</span>
                      </div>
                      <div className="bg-emerald-50 p-2 rounded-lg border border-emerald-100 flex justify-between items-center">
                          <div className="flex items-center gap-1">
                              <PieChart size={12} className="text-emerald-500"/>
                              <span className="text-[10px] font-black text-emerald-600 uppercase tracking-widest">Прибыль:</span>
                          </div>
                          <span className="text-sm font-black text-emerald-700 font-mono">+{f(economy.data.netProfit)} ₸</span>
                      </div>
                  </div>
                </>
              ) : (
                <div className="h-full flex flex-col items-center justify-center opacity-30 text-center">
                  <ShieldCheck size={32} className="mb-2"/>
                  <p className="text-[8px] font-black uppercase">Экономика скрыта</p>
                </div>
              )}
            </div>

            <div className={`p-3.5 border-t bg-slate-50 flex-none space-y-2.5 transition-all duration-300 ${isDescExpanded ? 'bg-white pt-4' : ''}`}>
              <div className="space-y-1">
                <label className="block text-[7px] font-black text-slate-400 uppercase ml-1 tracking-widest">Описание сборки</label>
                <textarea 
                  onFocus={() => setIsDescExpanded(true)}
                  className={`w-full bg-white border border-slate-200 rounded-lg p-2 text-[10px] font-bold text-slate-600 resize-none outline-none transition-all duration-300 shadow-sm ${isDescExpanded ? 'h-32 ring-2 ring-blue-500/5 border-blue-200' : 'h-10'}`}
                  placeholder="Особенности сборки..." 
                  value={config.bundleDescription} 
                  onChange={e => config.setBundleDescription(e.target.value)}
                />
              </div>
              {canSave && (
                <button 
                  onClick={handleSave} 
                  disabled={!machine}
                  className="w-full bg-blue-600 hover:bg-blue-700 disabled:opacity-30 disabled:grayscale text-white py-2.5 rounded-lg font-black uppercase text-[9px] tracking-widest shadow-lg transition-all active:scale-95 flex items-center justify-center gap-2"
                >
                  <Save size={12}/> {editingBundle ? 'ОБНОВИТЬ ШАБЛОН' : 'СОХРАНИТЬ ШАБЛОН'}
                </button>
              )}
            </div>
          </div>
        ) : (
          <div className="h-full flex flex-col items-center justify-center p-8 text-center opacity-30">
            <Calculator size={32} className="text-slate-300 mb-3 animate-pulse"/>
            <p className="text-[8px] font-black uppercase tracking-widest leading-relaxed">Выберите модель<br/>для расчетов</p>
          </div>
        )}
      </div>
    </div>
  );
};


interface OptionCardProps {
    type: OptionType;
    v: OptionVariant;
    machine: Product;
    configEntry: MachineConfigEntry | undefined;
    selectedVars: string[];
    exchangeRates: Record<Currency, number>;
    access: any; 
    config: any; 
    f: (val: number) => string;
}

const OptionCard: React.FC<OptionCardProps> = ({ type, v, machine, configEntry, selectedVars, exchangeRates, access, config, f }) => {

    const priceFromSource = useMemo(() => {
        return configEntry?.priceOverrides?.[v.id] ?? v.price;
    }, [v, configEntry]);
    
    const isDefault = BundleCalculator.getDefaultIds(configEntry).includes(v.id);

    return (
        <div 
            key={v.id} 
            onClick={() => config.toggleOption(type.id, v.id, type.isSingleSelect, type.isRequired)}
            className={`p-2 rounded-lg border-2 cursor-pointer transition-all flex flex-col justify-between min-h-[48px] ${selectedVars.includes(v.id) ? 'border-blue-500 bg-white shadow-sm shadow-blue-100' : 'border-slate-100 bg-white hover:border-blue-200'}`}>
            <div className="flex justify-between items-start gap-1.5">
                <span className={`text-xs font-bold leading-tight uppercase ${selectedVars.includes(v.id) ? 'text-blue-900' : 'text-slate-600'}`}>{v.name}</span>
                {selectedVars.includes(v.id) ? <CheckCircle size={12} className="text-blue-600"/> : <Circle size={12} className="text-slate-100"/>}
            </div>
            {access.canSee('fields', 'option_purchase_price') && (
                <div className="text-[10px] font-black font-mono text-slate-400 mt-1 flex items-center justify-between">
                    <div className="flex items-center gap-1.5">
                        <span className={isDefault ? "text-blue-500" : ""}>
                            {f(priceFromSource)} {v.currency}
                        </span>
                        {isDefault && (
                            <div className="flex items-center gap-0.5 bg-blue-50 text-blue-500 px-1 rounded text-[7px] font-black uppercase tracking-tighter">
                                <Star size={6} fill="currentColor"/> БАЗА
                            </div>
                        )}
                    </div>
                    {v.volumeM3 > 0 && (
                        <span className="text-blue-400 font-bold">+{v.volumeM3.toFixed(2)} м³</span>
                    )}
                </div>
            )}
        </div>
    );
};

const DetailRow = ({ label, value, bold = false, color = "text-slate-700" }: { label: string, value: number, bold?: boolean, color?: string }) => (
    <div className="flex justify-between items-center text-[11px]">
        <span className="text-slate-500 font-medium truncate pr-2">{label}:</span>
        <span className={`font-mono ${bold ? 'font-black' : 'font-bold'} ${color} whitespace-nowrap`}>{Math.round(value).toLocaleString()} ₸</span>
    </div>
);
